name: Build_Push_Docker_Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Docker_Build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout app code
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
          push: true
          tags: nvndocker/new-simple-nodejs-app:latest

